from .field import Field

GAME_NAME = "SNAKE"

WIDTH = 20
HEIGHT = 20
SCALE = 36
FIELD = Field(WIDTH, HEIGHT, SCALE)
FILL_SIZE = SCALE - 4

FPS = 60

START_SPEED = FPS
UP_SPEED_STEP = 1.25

HOLE_DISTANCE = 8
HOLE_LIFETIME = FPS * 10
HOLE_TIME_TO_SPAWN = FPS * 1
HOLE_TIME_TO_GROWTH = FPS * 2