from .field import Field

WIDTH = 20
HEIGHT = 20
SCALE = 30
FIELD = Field(WIDTH, HEIGHT, SCALE)
ELEMENT_SIZE = SCALE - 2

FPS = 60

START_SPEED = FPS // 2
UP_SPEED_DELAY = 2
UP_SPEED_STEP = 1.5

START_APPLE_LIFETIME = 10 * FPS